import { z } from "zod";

// 🔧 Local helpers (no external modules)
const uuidField = z.string().uuid({ message: "Invalid UUID format." });

const decimalField = z
  .string()
  .refine((val) => {
    const num = parseFloat(val);
    return !isNaN(num) && num >= 0.01;
  }, {
    message: "Price must be a valid number and at least 0.01.",
  })
  .transform((val) => parseFloat(val));

// ✅ Create ProductPrice schema
export const createProductPriceSchema = z.object({
    price: decimalField,
    productId: uuidField,
    priceTypeId: uuidField,
    tenantId: uuidField,
    subsidiaryId: uuidField,
    autoGenerated: z.boolean().optional(),
    editable: z.boolean().optional(),
});

// ✅ Update ProductPrice schema
export const updateProductPriceSchema = z.object({
    price: decimalField.optional(),
    autoGenerated: z.boolean().optional(),
    editable: z.boolean().optional(),
});

// ✅ ID param validation (:id)
export const productPriceIdSchema = z.object({
    id: uuidField,
});

// ✅ Subsidiary ID param validation (:subsidiaryId)
export const getProductPricesBySubsidiarySchema = z.object({
    subsidiaryId: uuidField,
});