import { Request, Response } from "express";
import prisma from "../../utils/prisma";
import { asyncHandler } from "../../utils/asyncHandler";
import { Prisma } from "../../../generated/prisma";
import Decimal from "decimal.js";

// ✅ Obtener precios por producto (con paginación, búsqueda por tipo y monto)
export const getPricesByProduct = asyncHandler(async (req: Request, res: Response) => {
  const { productId } = req.params;
  const { priceTypeId, search, page = "1", limit = "5" } = req.query;

  const product = await prisma.product.findUnique({
    where: { id: productId },
    include: {
      productCategory: { select: { name: true } },
      unitMeasurement: { select: { name: true } },
    },
  });

  if (!product) {
    return res.status(404).json({ message: "Producto no encontrado." });
  }

  const where: any = { productId };

  let filteredPriceTypeIds: string[] = [];

  if (search && String(search).trim().length >= 2) {
    const normalizedSearch = String(search)
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .replace(/ñ/gi, "n")
      .trim()
      .toLowerCase();

    const matchingTypes = await prisma.priceType.findMany({
      where: {
        name: { contains: normalizedSearch, mode: "insensitive" },
        subsidiaryId: product.subsidiaryId,
      },
      select: { id: true },
    });

    filteredPriceTypeIds = matchingTypes.map((pt) => pt.id);

    where.OR = [
      ...(filteredPriceTypeIds.length > 0
        ? [{ priceTypeId: { in: filteredPriceTypeIds } }]
        : []),
      ...(Number(search)
        ? [{ price: new Decimal(search as string) }]
        : []),
    ];
  }

  if (priceTypeId) {
    where.priceTypeId = String(priceTypeId);
  }

  const take = Math.max(Number(limit) || 5, 5);
  const skip = (Number(page) - 1) * take;

  const [total, prices] = await Promise.all([
    prisma.productPrice.count({ where }),
    prisma.productPrice.findMany({
      where,
      skip,
      take,
      include: {
        priceType: {
          select: {
            id: true,
            name: true,
            currency: { select: { code: true, name: true } },
          },
        },
      },
      orderBy: { priceType: { name: "asc" } },
    }),
  ]);

  res.json({
    product: {
      id: product.id,
      name: product.name,
      code: product.code,
      barcode: product.barcode,
      productCategory: product.productCategory,
      unitMeasurement: product.unitMeasurement,
    },
    total,
    page: Number(page),
    limit: take,
    totalPages: Math.ceil(total / take),
    prices,
  });
});

// ✅ Obtener un precio por su ID
export const getProductPriceById = asyncHandler(async (req: Request, res: Response) => {
  const { id } = req.params;

  const price = await prisma.productPrice.findUnique({
    where: { id },
    include: {
      priceType: {
        select: {
          id: true,
          name: true,
          currency: {
            select: {
              id: true,
              code: true,
              name: true,
            },
          },
        },
      },
      product: {
        select: {
          id: true,
          name: true,
          code: true,
          barcode: true,
        },
      },
    },
  });

  if (!price) {
    return res.status(404).json({ message: "Precio de producto no encontrado." });
  }

  res.json(price);
});

// ✅ Crear precio para un producto
export const createProductPrice = asyncHandler(async (req: Request, res: Response) => {
  const { productId } = req.params;
  const {
    priceTypeId,
    price,
    tenantId,
    subsidiaryId,
  } = req.body;

  const product = await prisma.product.findUnique({ where: { id: productId } });

  if (!product) {
    return res.status(404).json({ message: "Producto no encontrado." });
  }

  const exists = await prisma.productPrice.findFirst({
    where: {
      productId,
      priceTypeId,
      subsidiaryId,
    },
  });

  if (exists) {
    return res.status(409).json({
      message: "Ya existe un precio para este producto, tipo y sucursal.",
    });
  }

  const created = await prisma.productPrice.create({
    data: {
      productId,
      priceTypeId,
      price: new Decimal(price),
      tenantId,
      subsidiaryId,
      autoGenerated: false,
      editable: true,
    },
  });

  // 🔥 Devolver directamente el objeto
  res.status(201).json(created);
});

// ✅ Actualizar un precio existente (permitiendo editar autogenerados)
export const updateProductPrice = asyncHandler(async (req: Request, res: Response) => {
  const { id } = req.params;
  const { price } = req.body;

  const existing = await prisma.productPrice.findUnique({ where: { id } });

  if (!existing) {
    return res.status(404).json({ message: "Precio de producto no encontrado." });
  }

  const updated = await prisma.productPrice.update({
    where: { id },
    data: {
      price: new Decimal(price),
      editable: true,
      autoGenerated: false,
    },
  });

  res.json(updated);
});