import { Request, Response } from "express";
import prisma from "../../utils/prisma";
import { asyncHandler } from "../../utils/asyncHandler";

// ✅ Crear ProductPrice
export const createProductPrice = asyncHandler(async (req: Request, res: Response) => {
  const { productId, priceTypeId, price, autoGenerated, editable, tenantId, subsidiaryId } = req.body;

  // Verificar duplicado
  const exists = await prisma.productPrice.findFirst({
    where: {
      productId,
      priceTypeId,
      subsidiaryId,
    },
  });

  if (exists) {
    return res.status(409).json({
      message: "Product price with this price type already exists for this product and subsidiary.",
    });
  }

  const created = await prisma.productPrice.create({
    data: {
      productId,
      priceTypeId,
      price,
      autoGenerated: autoGenerated ?? true,
      editable: editable ?? false,
      tenantId,
      subsidiaryId,
    },
  });

  res.status(201).json({
    message: "Product price created successfully.",
    productPrice: created,
  });
});

// ✅ Actualizar ProductPrice
export const updateProductPrice = asyncHandler(async (req: Request, res: Response) => {
  const { id } = req.params;
  const { price, autoGenerated, editable } = req.body;

  const existing = await prisma.productPrice.findUnique({ where: { id } });

  if (!existing) {
    return res.status(404).json({ message: "Product price not found." });
  }

  const updated = await prisma.productPrice.update({
    where: { id },
    data: {
      price: price ?? undefined,
      autoGenerated: autoGenerated ?? undefined,
      editable: editable ?? undefined,
    },
  });

  res.json({
    message: "Product price updated successfully.",
    productPrice: updated,
  });
});

// ✅ Obtener ProductPrice por ID
export const getProductPriceById = asyncHandler(async (req: Request, res: Response) => {
  const { id } = req.params;

  const productPrice = await prisma.productPrice.findUnique({
    where: { id },
    include: {
      product: { select: { id: true, name: true, code: true } },
      priceType: { select: { id: true, name: true } },
    },
  });

  if (!productPrice) {
    return res.status(404).json({ message: "Product price not found." });
  }

  res.json(productPrice);
});

// ✅ Obtener todos los ProductPrices por sucursal
export const getProductPricesBySubsidiary = asyncHandler(async (req: Request, res: Response) => {
  const { subsidiaryId } = req.params;

  const productPrices = await prisma.productPrice.findMany({
    where: { subsidiaryId },
    include: {
      product: { select: { id: true, name: true, code: true } },
      priceType: { select: { id: true, name: true } },
    },
    orderBy: { product: { name: "asc" } },
  });

  res.json({
    total: productPrices.length,
    productPrices,
  });
});