import prisma from "../../src/utils/prisma";
import { ProductPrice } from "../../generated/prisma";

export async function seedProductPrices(
  subsidiaries,
  products,
  priceTypes,
  currencies
): Promise<ProductPrice[]> {
  console.log("🏷️ Seeding ProductPrices...");

  const createdPrices: ProductPrice[] = [];

  for (const s of subsidiaries) {
    if (
      s.id === "00000000-0000-0000-0000-000000000000" ||
      s.tenantId === "00000000-0000-0000-0000-000000000000"
    ) {
      console.log(`⏭️ Skipping subsidiary ${s.id} for product prices.`);
      continue;
    }

    const productsBySubsidiary = products.filter(p => p.subsidiaryId === s.id);
    const usd = currencies.find(c => c.code === "USD" && c.subsidiaryId === s.id);
    const minorista = priceTypes.find(p => p.name === "Minorista" && p.subsidiaryId === s.id);
    const mayorista = priceTypes.find(p => p.name === "Mayorista" && p.subsidiaryId === s.id);

    if (!usd || !minorista || !mayorista) {
      console.warn(`⚠️ Skipping ${s.id} → Missing USD or priceTypes`);
      continue;
    }

    for (const prod of productsBySubsidiary) {
      const costBase = 1.00;
      const priceMinorista = costBase * (1 + (minorista.marginPercent || 0) / 100);
      const priceMayorista = costBase * (1 + (mayorista.marginPercent || 0) / 100);

      const price1 = await prisma.productPrice.create({
        data: {
          productId: prod.id,
          priceTypeId: minorista.id,
          currencyId: usd.id,
          amount: priceMinorista,
          autoGenerated: true,
          tenantId: s.tenantId,
          subsidiaryId: s.id,
        },
      });
      createdPrices.push(price1);

      const price2 = await prisma.productPrice.create({
        data: {
          productId: prod.id,
          priceTypeId: mayorista.id,
          currencyId: usd.id,
          amount: priceMayorista,
          autoGenerated: true,
          tenantId: s.tenantId,
          subsidiaryId: s.id,
        },
      });
      createdPrices.push(price2);
    }
  }

  console.log(`🏷️ Total product prices created: ${createdPrices.length}`);
  return createdPrices;
}