import prisma from "../../src/utils/prisma";
import { ProductPrice } from "../../generated/prisma";

export async function seedProductPrices(
  subsidiaries,
  products,
  priceTypes,
  currencies,
  priceMargins
) {
  console.log("🏷️ Seeding ProductPrices...");

  const createdPrices: ProductPrice[] = [];

  for (const s of subsidiaries) {
    if (
      s.id === "00000000-0000-0000-0000-000000000000" ||
      s.tenantId === "00000000-0000-0000-0000-000000000000"
    ) {
      console.log(`⏭️ Skipping subsidiary ${s.id} for product prices.`);
      continue;
    }

    // 🧐 Valida arrays antes de usar find
    if (!Array.isArray(products)) {
      console.warn(`⚠️ Products is undefined for ${s.id}`);
      continue;
    }
    if (!Array.isArray(priceTypes)) {
      console.warn(`⚠️ PriceTypes is undefined for ${s.id}`);
      continue;
    }
    if (!Array.isArray(currencies)) {
      console.warn(`⚠️ Currencies is undefined for ${s.id}`);
      continue;
    }
    if (!Array.isArray(priceMargins)) {
      console.warn(`⚠️ PriceMargins is undefined for ${s.id}`);
      continue;
    }

    const prod = products.find(p => p.code === "LAP-BIC-BLU" && p.subsidiaryId === s.id);
    const usd = currencies.find(c => c.code === "USD" && c.subsidiaryId === s.id);
    const minorista = priceTypes.find(p => p.name === "Minorista" && p.subsidiaryId === s.id);
    const mayorista = priceTypes.find(p => p.name === "Mayorista" && p.subsidiaryId === s.id);

    const marginMin = priceMargins.find(m => m.priceTypeId === minorista?.id);
    const marginMay = priceMargins.find(m => m.priceTypeId === mayorista?.id);

    if (!prod || !usd || !minorista || !mayorista) {
      console.warn(`⚠️ Skipping ${s.id} → Missing prod/usd/priceType`);
      continue;
    }

    const costBase = 1.00;
    const priceMinorista = costBase * (1 + (marginMin?.marginPercent || 0) / 100);
    const priceMayorista = costBase * (1 + (marginMay?.marginPercent || 0) / 100);

    const price1 = await prisma.productPrice.create({
      data: {
        productId: prod.id,
        priceTypeId: minorista.id,
        currencyId: usd.id,
        amount: priceMinorista,
        autoGenerated: true,
        tenantId: s.tenantId,
        subsidiaryId: s.id,
      },
    });
    createdPrices.push(price1);

    const price2 = await prisma.productPrice.create({
      data: {
        productId: prod.id,
        priceTypeId: mayorista.id,
        currencyId: usd.id,
        amount: priceMayorista,
        autoGenerated: true,
        tenantId: s.tenantId,
        subsidiaryId: s.id,
      },
    });
    createdPrices.push(price2);
  }

  console.log(`🏷️ Total product prices created: ${createdPrices.length}`);
  return createdPrices;
}
