import { Decimal } from '@prisma/client/runtime/library';
import { faker } from '@faker-js/faker';
import prisma from '../../src/utils/prisma';
import {
  Product,
  Subsidiary,
  Currency,
  PriceType,
  ExchangeRate,
  ProductPrice, // ✅ Asegúrate de importar ProductPrice
} from '../../generated/prisma';

export async function seedProductPrices({
  products,
  subsidiaries,
  currencies,
  priceTypes,
  exchangeRates,
}: {
  products: Product[];
  subsidiaries: Subsidiary[];
  currencies: Currency[];
  priceTypes: PriceType[];
  exchangeRates: ExchangeRate[];
}) {
  console.log('💰 Seeding Product Prices...');

  const createdPrices: ProductPrice[] = []; // ✅ Tipo explícito aquí

  for (const product of products) {
    if (
      product.id === '00000000-0000-0000-0000-000000000000' ||
      product.tenantId === '00000000-0000-0000-0000-000000000000'
    ) {
      continue;
    }

    const productSubsidiary = subsidiaries.find((s) => s.id === product.subsidiaryId);
    if (!productSubsidiary) continue;

    for (const priceType of priceTypes) {
      for (const currency of currencies.filter((c) => c.tenantId === product.tenantId)) {
        const exchangeRate = exchangeRates.find(
          (r) =>
            r.tenantId === product.tenantId &&
            r.toCurrencyId === currency.id &&
            r.subsidiaryId === product.subsidiaryId
        );

        if (!exchangeRate) {
          console.warn(`⚠️ No exchange rate for ${currency.code} in ${product.subsidiaryId}`);
          continue;
        }

        // Base price in USD
        const basePrice =
          product.lastPurchasePriceUSD ||
          new Decimal(faker.number.float({ min: 2, max: 15, fractionDigits: 2 }));

        // Aplicar margen de ganancia
        const marginMap: Record<string, number> = {
          MINORISTA: 0.4,
          MAYORISTA: 0.3,
          FACTURADO: 0.5,
        };

        const margin = marginMap[priceType.name.toUpperCase()] ?? 0.4;
        const finalUSD = basePrice.mul(Decimal.add(1, margin));
        const finalPrice = currency.code === 'USD' ? finalUSD : finalUSD.mul(exchangeRate.rate);

        const price = await prisma.productPrice.create({
          data: {
            amount: finalPrice,
            autoGenerated: true,
            tenantId: product.tenantId,
            subsidiaryId: product.subsidiaryId,
            productId: product.id,
            priceTypeId: priceType.id,
            currencyId: currency.id,
          },
        });

        createdPrices.push(price); // ✅ ya no da error
        console.log(
          `✅ Price ${finalPrice.toFixed(2)} ${currency.code} for ${product.name} [${priceType.name}]`
        );
      }
    }
  }

  console.log(`💾 Total product prices created: ${createdPrices.length}`);
  return createdPrices;
}